import { env } from '@/lib/env'
import { social } from '@/lib/social'
import type { Person, WithContext } from 'schema-dts'

const protocol = process.env.NODE_ENV === 'production' ? 'https' : 'http'
const baseUrl = `${protocol}://${env.VERCEL_PROJECT_PRODUCTION_URL}`

const person: WithContext<Person> = {
	'@context': 'https://schema.org',
	'@type': 'Person',
	name: 'Marwan Shehata',
	description: 'Frontend Web Developer',
	gender: 'male',
	nationality: 'Egyptian',
	url: baseUrl,
	image: new URL('/profile.jpg', baseUrl).toString(),
	sameAs: Object.values(social).map(({ href }) => href),
	alumniOf: 'Alexandria University',
	knowsAbout: [
		'Web Development',
		'Frontend Development',
		'React',
		'Next.js',
		'TypeScript',
		'JavaScript',
		'HTML',
		'CSS',
		'Sass',
		'Tailwind CSS',
		'Node.js',
		'Express.js',
		'MongoDB',
		'PostgreSQL',
		'Prisma',
		'GraphQL',
		'RESTful APIs',
		'Git',
		'GitHub',
		'GitLab',
		'Docker',
		'Kubernetes',
		'AWS',
		'Azure',
		'Google Cloud',
		'Heroku',
		'Vercel',
		'Netlify',
		'Vite',
		'Webpack',
		'Babel',
		'ESLint',
		'Prettier',
		'Jest',
		'React Testing Library',
		'Cypress',
		'Playwright',
		'Puppeteer',
		'Selenium',
		'Jira',
		'Confluence',
		'Slack',
		'Trello',
		'Asana',
		'Figma',
		'Adobe XD',
		'Sketch',
		'Invision',
		'Zeplin',
		'Notion',
		'Miro',
		'Framer',
		'Figma',
	],
	jobTitle: 'Frontend Web Developer',
	worksFor: {
		'@type': 'Organization',
		name: 'Euclid Solutions',
		url: 'https://site.takhz.in/',
	},
}

export const JsonLd = () => (
	<script type='application/ld+json'>{JSON.stringify(person)}</script>
)
